# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'default_permissions': ()},
        ),
    ]
