# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20161017_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
